#!/bin/bash

FILE="$HOME/.whereto"

while test $# -gt 0; do
    case "$1" in 
        -h|--help)
            echo "where to? - directory teleporter."
            echo "Teleport to a directory in which you have previously set a portal."
            echo "to [flags] [location]"
            echo "Flags:"
            echo "-a | --add         Adds a portal to the current directory in the index."
            echo "-e | --edit        Edit the index."
            echo "-h | --help        show usage."
            exit 0
            ;;
        -a|--add)
            eval pwd >> $FILE
            exit 0 
            ;;
        -e|--edit)
            eval vim $FILE
            exit 0
            ;;
        *)
            break
            ;;
        
    esac
done

#edit - open file in vim
function e()
{
eval vim $FILE
} 

# add (pipe in the current directory)
#eval FILE < pwd


# usage / help


# teleport 
